### PR TITLE
Re-organized theme, Glide Add, Login indicator, Fix crash at user-detail, etc

### PR DESCRIPTION
**Pull request by XinyueZ**
- Also fixed some sites that have potenial null-ptr problems.
- Add login indicator when login.
- Use TextInputEditText and TextInputLayout to handle input error on "hello".
- Chinese support for "register unsuccessfully".
- Support "enter" login instead dismiss keyword and click manually.
- Use Glide to load "checkcode", but not works , can not get image, check backend is needed.
- Re-organized theme files of the app, specify a theme to "hello" pages.
- **Reduce class structor of activites.**  @21037ad

### CODE REVIEW

**Comment by Thereisnospon** [comment]
using glide to show check code?  i think it may let register failure,because i use okhttp request checkcode use cookie. are you sure register (request check code)still work?

**Comment by Thereisnospon** [comment]
@

**Comment by XinyueZ** [comment]
@Thereisnospon The idea of using Glide is that this library brings stable image-loading process. OK, it might be some confused collections on me, but I'd reset this change when cookie will be used for this train.  Some reason of this change is that I've never seen an image or something like when the app tries to get "check code" from server.

? Might be good this http://stackoverflow.com/questions/28106527/glide-adding-header-to-request

**Comment by Thereisnospon** [comment]
@XinyueZ  i fixed it (checkcode)

**Pull request merged**
