### PR TITLE
Gradle, databinding update

### PR DESCRIPTION
**Pull request by XinyueZ**
1. app/build.gradle  update for SDK, tool, add flag for support-vector-drawable, databinding.
2. use gradle.properties 
3. use Google databinding
4. remove butterknife

### CODE REVIEW

**Comment by Thereisnospon** [comment]
数据绑定导致个人信息详情页UserDetailFragment错误。
` Caused by: java.lang.RuntimeException: view tag isn't correct on view:null
                                                       at thereisnospon.acclient.databinding.FragmentUserDetailWrapperBinding.bind(FragmentUserDetailWrapperBinding.java:119)`

**Comment by XinyueZ** [comment]
@Thereisnospon I'll check it.

**Comment by XinyueZ** [comment]
@Thereisnospon done

**Comment by Thereisnospon** [comment]
@XinyueZ  ok

**Pull request merged**
